---
- name: Converge
  hosts: all
  tasks:
    - name: apt update cache
      apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

- import_playbook: /home/ggeorgiev/ansible-apache2/main.yml
